### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mazeeblanke** [sergiodxa/next-nprogress#102]
After following the installation steps i get the following error:

Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at sanitize (C:\Users\mazino.ukah\ReactProjects\Treten\TretenFE\node_modules\styled-jsx\dist\stylesheet-registry.js:21:15)

**Comment by Protectator** [comment]
This is a duplicate of https://github.com/sergiodxa/next-nprogress/issues/76

**Comment by sergiodxa** [comment]
Hello,

I'm not maintaining this anymore because I'm not using it anymore in my projects and I don't have time to work on it.

Feel free to fork and publish to npm with another name.
