### ISSUE TITLE
Progress bar not stopping, or firing unnecessarily 

### ISSUE THREAD

**Issue by adueck** [sergiodxa/next-nprogress#18]
I have noticed that in some situations the progress bar gets fired unnecessarily, or slowly trickles away without getting stopped.

This happens a lot in Firefox, and sometimes in Chrome (a lot in dev, sometimes in production).

Here are two examples of when I see it happen. 
(With Chrome in dev sometimes, and almost always with Firefox in production)

- when clicking on a `<Link>` to another page within the next app. The progress bar fires, but it doesn't finish when the page loads. It just slowly keeps trickling and gets stuck near the end.

- when changing to a different page using `Router.replace('/new-page.js')`, the progress bar keeps trickling and doesn't stop when the new page is loaded.

- sometimes I need to make a POST html request to an api (database backend), *without* changing pages. But when the POST requests goes, the progress bar starts loading. Then it just trickles away and gets stuck at almost full.

Then it stays stuck there, even if I change pages. I need to refresh to get it back to normal.

How can we prevent the progress bar from firing in situations like this? Has this addon been tested extensively with Firefox?

**edit**: I imagine this is a problem with `next/router`, it shouldn't be firing `onRouteChangeStart` on POST requests that don't change the page, and it seems to not be firing `onRouteChangeComplete` in a lot of situations (especially with Firefox).

**Comment by sergiodxa** [comment]
I have not tried it in Firefox at all. But I agree it's may be a bug with next/router since the actual code of this module is too tiny.

**Comment by adueck** [comment]
Yes, defiantly an issue with next/router. It fails to 'finish' in a lot of situations. (POST requests, page changes in Firefox etc.)
