### ISSUE TITLE
NPM package not updated

### ISSUE THREAD

**Issue by guivr** [sergiodxa/next-nprogress#19]
The NPM version of this package is not updated with the new Component feature

**Comment by guivr** [comment]
I also tried to download it by myself but still with problems on npm install to download the modules

![image](https://user-images.githubusercontent.com/7696343/47270802-47df2200-d547-11e8-9ff5-46974b8b6f98.png)

**Comment by sergiodxa** [comment]
This is now published as the version 1.2.0.
