### ISSUE TITLE
Router is not defined

### ISSUE THREAD

**Issue by poeti8** [sergiodxa/next-nprogress#21]
Trying to use the NProgress component but it breaks the app.
```
ReferenceError: Router is not defined
```

I see that you're using Router in [component.js](https://github.com/sergiodxa/next-nprogress/blob/master/src/component.js), but you're not importing it from next.

**Comment by guivr** [comment]
Same here

**Comment by guivr** [comment]
This wasn't fixed for me, here. Or probably is the npm again
