### ISSUE TITLE
Latest fix 'React is not defined' is not published to npm

### ISSUE THREAD

**Issue by itsfadnis** [sergiodxa/next-nprogress#26]
_Originally posted by @itsfadnis in https://github.com/sergiodxa/next-nprogress/pull/23#issuecomment-432998639_

Can you please publish? Thanks.

**Comment by brianlovin** [comment]
Hoping to bump this - the latest version of React breaks with 1.2.0 of next-nprogress; would love to update both, and seems like the fix has landed just not been published :)

**Comment by wrick17** [comment]
Bump!

**Comment by sergiodxa** [comment]
Latest changes including the fix of #23 are published to npm as 1.3.0.

Sorry for the delay to publish it.

**Comment by brianlovin** [comment]
Hero, thank you @sergiodxa!!
