### ISSUE TITLE
Error since version 1.4.0

### ISSUE THREAD

**Issue by axeff** [sergiodxa/next-nprogress#39]
` ERROR  Failed to compile with 1 errors                                                                                                                                    09:15:12

This relative module was not found:

* ./dist/styles.js in ./node_modules/next-nprogress/styles.js`

**Comment by sergiodxa** [comment]
`styles` component was removed since is now automatically added by the HOC or the component implementation.

Thinking now about this it should have been a major release, sorry for that.
