### ISSUE TITLE
Using along with next-ga

### ISSUE THREAD

**Issue by arherzf8er** [sergiodxa/next-nprogress#47]
Could you please tell how can I use this with your great `next-ga` package? Thanks in advance!

**Comment by sergiodxa** [comment]
Hi! You could check how I used them on my own blog https://github.com/sergiodxa/personal-site/blob/master/pages/_app.js that file specifically.

**Comment by sergiodxa** [comment]
Will close this if you don't have more questions, reopen it if you still can't use them together.
