### ISSUE TITLE
@types/next-nprogress is required

### ISSUE THREAD

**Issue by mattdamon108** [sergiodxa/next-nprogress#52]
Hi~ 👋 
Thank you for your wonderful library.

I'd like to use it in _app.tsx, but it throws an error says @types/next-nprogress is required or add *.d.ts containing `declare module next-nprogress`. I tried to `yarn add @types/next-nprogress -D`, but failed not found.

any solution?

**Comment by sergiodxa** [comment]
Hi! I don't use typescript and I'm pretty sure there is no community made for definitions for this module. So I'm afraid you are on your own defining them.

If you get it working you could publish them to help other people in the future 🙏

**Comment by Ovyerus** [comment]
For posterity, I recently added definitions for this project to the DefinitelyTyped repo, so installing them should work fine now. http://npmjs.com/@types/next-nprogress
