### ISSUE TITLE
When using hoc props are no longer passed

### ISSUE THREAD

**Issue by decebal** [sergiodxa/next-nprogress#83]
I have taken some time to research this one.
It looks like the release for fixing #4 also improved the way nprogress can be attached,which is just by using the hoc, no more need for adding the NProgress component, however configuring NProgress has been obfuscated.

It is no longer possible to overwrite the default Props of NProgress which remain the default: 
```
color: "#2299DD",
showAfterMs: 300,
spinner: true
```
also the property `delayMs` is misconfigured as it should be `showAfterMs`.

**Comment by VinceBT** [comment]
Can this be merged @sergiodxa ?

**Comment by balazsnemeth** [comment]
Can we have this merged?

**Comment by sergiodxa** [comment]
Hello,

I'm not maintaining this anymore because I'm not using it anymore in my projects and I don't have time to work on it.

Feel free to fork and publish to npm with another name.
